### ISSUE TITLE
Some equivalent function in R package ('wmtsa') not available in pywt, e.g. wavVar()

### ISSUE THREAD

**Issue by fairymane** [nigma/pywt#8]
Hi, 
I am trying to implement some wavelet analysis in Python for some R code wrote previously. 

One function used in earlier R version code is discrete wavelet variance estimation ( 'wmtsa', page69,<http://cran.r-project.org/web/packages/wmtsa/wmtsa.pdf>). But I couldn't find equivalent function to implement in pywt package. Does any one knows alternative solution to that if I want to implement the similar function in Python?

Thanks!
Tao

**Comment by rgommers** [comment]
The DWT based version might not be too hard to implement, but the R default is based on MODWT which is not present in PyWavelets. So that likely won't materialize any time soon. @fairymane do you have an idea about the performance difference between DWT and MODWT, and would DWT-based variance estimation be of use to you?

**Comment by rgommers** [comment]
Hi @fairymane, development has moved to https://github.com/PyWavelets/pywt, so I've moved your feature request there and am closing this issue. Thanks for your interest!
